version: "1.0"
info:
  model: int-scaffold
packages:
- name: ExternalGitProjectProject
  gitServerName: SanthoshK7D
  gitUrl: https://github.com/santhu736852/ExternalGitProjectProject
  gitUsername: santhu736852
  gitBranch: main
